### ISSUE TITLE
Limit Rancher Reservation

### ISSUE THREAD

**Issue by AJMansfield** [AJMansfield/sentinel-k8s-deployment#6]
See information gathered in #5 

Rancher, NGINX, and the relevant proxy services, are reserving too much CPU (that they don't even use).

**Comment by AJMansfield** [comment]
This is probably lower priority than the other resource caps.
In theory, the "full production" version will be totally headless and noninteractable, so rancher is probably not even needed except for development clusters.

**Comment by AJMansfield** [comment]
Targets are:
- rke2-ingress-nginx-controller -- 300m total, 100m per
- kube-proxy -- 750m total, 250m per

**Comment by AJMansfield** [comment]
`rke2-ingress-nginx` is controlled by the `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml` manifest.

This derives from rke2-charts here: https://github.com/rancher/rke2-charts/tree/c748bc05d05ef4fc147670e395adfeaa96bafdd9/packages/rke2-ingress-nginx

rke2 has some customization patches; the main thing changed is converting it from a Deployment to a DaemonSet

The file being patched is this: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.1.0/ingress-nginx-4.1.0.tgz

This derives from this source repo: https://github.com/kubernetes/ingress-nginx/

This chart has [values.yaml](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml) that defines multiple different resources bounds blocks, but the most relevant seems to be
[L321-L327](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L321-L327)

Excerpt from values tree:
```yaml
controller:
  ## Define requests resources to avoid probe issues due to CPU utilization in busy nodes
  ## ref: https://github.com/kubernetes/ingress-nginx/issues/4735#issuecomment-551204903
  ## Ideally, there should be no limits.
  ## https://engineering.indeedblog.com/blog/2019/12/cpu-throttling-regression-fix/
  resources:
    ##  limits:
    ##    cpu: 100m
    ##    memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi
  admissionWebhooks:
    createSecretJob:
      resources: {}
      # limits:
      #   cpu: 10m
      #   memory: 20Mi
      # requests:
      #   cpu: 10m
      #   memory: 20Mi
    patchWebhookJob:
      resources: {}
defaultBackend:
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
```
