### ISSUE TITLE
Limit RKE2 CNI Reservation

### ISSUE THREAD

**Issue by AJMansfield** [AJMansfield/sentinel-k8s-deployment#8]
See information gathered in #5

- [ ] Determine if some CNI features can be disabled
  - [ ] Do we really need canal?
  - [ ] Do we need two different kinds of DHCP services?
  - [ ] Verify that the IPAM DHCP daemon we were using earlier is fully removed.
- [ ] Profile CPU usage of CNI services under load.
- [ ] Research how to configure RKE2 resource limits.
  - [ ] Is this a rke2/config.yaml item or a manifest/helmchartconfig item?
  - [ ] What are the config keys that control this?
- [ ] Set appropriate limits.

**Comment by AJMansfield** [comment]
Services that need to be reduced:

- rke2-canal
- rke2-multus
- rke2-coredns

**Comment by AJMansfield** [comment]
rke2-canal CPU limit is set here:
https://github.com/rancher/rke2-charts/blob/c748bc05d05ef4fc147670e395adfeaa96bafdd9/packages/rke2-canal/charts/templates/daemonset.yaml#L184-L186

It's a DaemonSet configured to reserve 250m per node.

This reservation is not templated from a config value.

Should I propose an upstream change, or perhaps use my own fork?
Or is there an overlay mechanism to be used instead? (e.g. Kustomize?)

**Comment by AJMansfield** [comment]
rke2-coredns is a helm chart with patch files that live in rke2-charts [here](https://github.com/rancher/rke2-charts/tree/main-source/packages/rke2-coredns), while the base package is frozen to coredns-1.24.0 which derives from repository source that lives [here](https://github.com/coredns/helm/tree/master/charts/coredns).

There are two components: an autoscaler and the actual deployment.

### Autoscaler
The autoscaler (`rke2-coredns-rke2-coredns-autoscaler`) sets these resources:
```yaml
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 16Mi
```
The source location for this limit is [here](https://github.com/coredns/helm/blob/coredns-1.24.0/charts/coredns/templates/deployment-autoscaler.yaml#L79-L80)
It uses helm templates to pull from the chart values, which uses a config block with these defaults:
```yaml
autoscaler:
  resources:
    requests:
      cpu: "20m"
      memory: "10Mi"
    limits:
      cpu: "20m"
      memory: "10Mi"
```

Interesting! That's not what RKE2 defaulted to.

The RKE2 patch actually overrides this default [here](
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-coredns/generated-changes/patch/values.yaml.patch#L137-L148).

This should be easily customizable with a HelmChartConfig in the rke2 manifests folder.

### Main Deployment

The main deployment (`rke2-coredns-rke2-coredns`) sets these resources:
```yaml
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
The source location for this limit is [here](https://github.com/coredns/helm/blob/coredns-1.24.0/charts/coredns/templates/deployment.yaml#L116)
It uses helm templates to pull from the values file, which uses a config block with these defaults:
```yaml
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

This too should be easily customizable with a HelmChartConfig in the rke2 manifests folder.
